name: Rust

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: dbg mdfind on macOS 
        if: matrix.os = 'macos-latest'
        run: |
          mdfind "kMDItemKind == 'Application'"
          mdfind "kMDItemContentType = 'com.apple.application-bundle'"
          mdfind -onlyin / "kMDItemKind == 'Application'"
          mdfind -onlyin / "kMDItemContentType = 'com.apple.application-bundle'"

      # - name: Build
      #   run: cargo build --verbose

      # - name: Run tests
      #   run: cargo test --verbose
